-- Catálogos usados pelo perfil e pelo marketplace.

CREATE TABLE cursos (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(120) NOT NULL,
    CONSTRAINT uk_cursos_nome UNIQUE (nome)
);

CREATE TABLE areas_conhecimento (
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(120) NOT NULL,
    CONSTRAINT uk_areas_conhecimento_nome UNIQUE (nome)
);

-- Cada habilidade pertence a uma área; a área não pode ser apagada enquanto tiver habilidades.
CREATE TABLE habilidades (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome    varchar(120) NOT NULL,
    area_id bigint       NOT NULL REFERENCES areas_conhecimento (id),
    CONSTRAINT uk_habilidades_nome UNIQUE (nome)
);

CREATE INDEX idx_habilidades_area ON habilidades (area_id);
