-- Usuários (login por e-mail) e suas configurações.

CREATE TABLE usuarios (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(254) NOT NULL,
    nome          varchar(120) NOT NULL,
    senha_hash    varchar(100) NOT NULL,
    -- Campos do perfil, preenchidos depois do cadastro.
    curso_id      bigint       REFERENCES cursos (id) ON DELETE SET NULL,
    periodo       smallint,
    cidade        varchar(120),
    bio           varchar(1000),
    foto_url      varchar(500),
    criado_em     timestamptz  NOT NULL DEFAULT now(),
    atualizado_em timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_email_minusculo CHECK (email = lower(email)),
    CONSTRAINT ck_usuarios_periodo CHECK (periodo BETWEEN 1 AND 20)
);

CREATE INDEX idx_usuarios_curso ON usuarios (curso_id);

-- 1:1 com usuarios. Defaults iguais ao CONFIG_PADRAO do front.
CREATE TABLE configuracoes_usuario (
    usuario_id          bigint      PRIMARY KEY REFERENCES usuarios (id) ON DELETE CASCADE,
    tema                varchar(20) NOT NULL DEFAULT 'light',
    perfil_publico      boolean     NOT NULL DEFAULT true,
    mostrar_email       boolean     NOT NULL DEFAULT false,
    permitir_mensagens  boolean     NOT NULL DEFAULT true,
    novas_oportunidades boolean     NOT NULL DEFAULT true,
    mensagens           boolean     NOT NULL DEFAULT true,
    conexoes            boolean     NOT NULL DEFAULT true,
    publicacoes         boolean     NOT NULL DEFAULT true,
    resumo_semanal      boolean     NOT NULL DEFAULT false,
    reduzir_animacoes   boolean     NOT NULL DEFAULT false,
    CONSTRAINT ck_configuracoes_usuario_tema CHECK (tema IN ('light', 'dark'))
);

-- Habilidades que o usuário declara ter (nível opcional).
CREATE TABLE usuario_habilidades (
    usuario_id    bigint      NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    habilidade_id bigint      NOT NULL REFERENCES habilidades (id) ON DELETE CASCADE,
    nivel         varchar(20),
    PRIMARY KEY (usuario_id, habilidade_id),
    CONSTRAINT ck_usuario_habilidades_nivel CHECK (nivel IN ('BASICO', 'INTERMEDIARIO', 'AVANCADO'))
);

CREATE INDEX idx_usuario_habilidades_habilidade ON usuario_habilidades (habilidade_id);

-- Áreas de interesse do usuário.
CREATE TABLE usuario_interesses (
    usuario_id bigint NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    area_id    bigint NOT NULL REFERENCES areas_conhecimento (id) ON DELETE CASCADE,
    PRIMARY KEY (usuario_id, area_id)
);

CREATE INDEX idx_usuario_interesses_area ON usuario_interesses (area_id);
