-- Domínio do marketplace: oportunidades, habilidades publicadas e interações.

-- Oportunidade publicada por um usuário (projeto, freela, monitoria etc.).
CREATE TABLE oportunidades (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autor_id      bigint       NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    tipo          varchar(20)  NOT NULL,
    titulo        varchar(150) NOT NULL,
    descricao     text         NOT NULL,
    modalidade    varchar(20)  NOT NULL,
    status        varchar(20)  NOT NULL DEFAULT 'ABERTA',
    criado_em     timestamptz  NOT NULL DEFAULT now(),
    atualizado_em timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_oportunidades_tipo CHECK (tipo IN ('PROJETO', 'CONSULTORIA', 'PESQUISA', 'DESIGN', 'FREELA', 'MONITORIA', 'AULA')),
    CONSTRAINT ck_oportunidades_modalidade CHECK (modalidade IN ('REMOTO', 'HIBRIDO', 'PRESENCIAL')),
    CONSTRAINT ck_oportunidades_status CHECK (status IN ('ABERTA', 'FECHADA'))
);

CREATE INDEX idx_oportunidades_autor ON oportunidades (autor_id);
-- Listagem padrão: abertas, mais recentes primeiro.
CREATE INDEX idx_oportunidades_status_criado ON oportunidades (status, criado_em DESC);

CREATE TABLE oportunidade_areas (
    oportunidade_id bigint NOT NULL REFERENCES oportunidades (id) ON DELETE CASCADE,
    area_id         bigint NOT NULL REFERENCES areas_conhecimento (id) ON DELETE CASCADE,
    PRIMARY KEY (oportunidade_id, area_id)
);

CREATE INDEX idx_oportunidade_areas_area ON oportunidade_areas (area_id);

CREATE TABLE oportunidade_habilidades (
    oportunidade_id bigint NOT NULL REFERENCES oportunidades (id) ON DELETE CASCADE,
    habilidade_id   bigint NOT NULL REFERENCES habilidades (id) ON DELETE CASCADE,
    PRIMARY KEY (oportunidade_id, habilidade_id)
);

CREATE INDEX idx_oportunidade_habilidades_habilidade ON oportunidade_habilidades (habilidade_id);

-- O que o aluno oferece ("Publicar habilidade"); entidade separada de oportunidades.
CREATE TABLE habilidades_publicadas (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    bigint       NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    habilidade_id bigint       NOT NULL REFERENCES habilidades (id),
    titulo        varchar(150) NOT NULL,
    descricao     text         NOT NULL,
    modalidade    varchar(20)  NOT NULL,
    ativa         boolean      NOT NULL DEFAULT true,
    criado_em     timestamptz  NOT NULL DEFAULT now(),
    atualizado_em timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_habilidades_publicadas_modalidade CHECK (modalidade IN ('REMOTO', 'HIBRIDO', 'PRESENCIAL'))
);

CREATE INDEX idx_habilidades_publicadas_usuario ON habilidades_publicadas (usuario_id);
CREATE INDEX idx_habilidades_publicadas_habilidade ON habilidades_publicadas (habilidade_id);

-- Pedido de um usuário para participar de uma oportunidade.
CREATE TABLE participacoes (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oportunidade_id bigint      NOT NULL REFERENCES oportunidades (id) ON DELETE CASCADE,
    usuario_id      bigint      NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    status          varchar(20) NOT NULL DEFAULT 'PENDENTE',
    criado_em       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_participacoes_par UNIQUE (oportunidade_id, usuario_id),
    CONSTRAINT ck_participacoes_status CHECK (status IN ('PENDENTE', 'ACEITA', 'RECUSADA'))
);

CREATE INDEX idx_participacoes_usuario ON participacoes (usuario_id);

-- Pedido de contratação de uma habilidade publicada.
CREATE TABLE contratacoes (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    habilidade_publicada_id bigint      NOT NULL REFERENCES habilidades_publicadas (id) ON DELETE CASCADE,
    solicitante_id          bigint      NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    mensagem                varchar(1000),
    status                  varchar(20) NOT NULL DEFAULT 'PENDENTE',
    criado_em               timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_contratacoes_par UNIQUE (habilidade_publicada_id, solicitante_id),
    CONSTRAINT ck_contratacoes_status CHECK (status IN ('PENDENTE', 'ACEITA', 'RECUSADA'))
);

CREATE INDEX idx_contratacoes_solicitante ON contratacoes (solicitante_id);

-- Item salvo: exatamente um entre oportunidade e habilidade publicada.
CREATE TABLE itens_salvos (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id              bigint      NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    oportunidade_id         bigint      REFERENCES oportunidades (id) ON DELETE CASCADE,
    habilidade_publicada_id bigint      REFERENCES habilidades_publicadas (id) ON DELETE CASCADE,
    criado_em               timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_itens_salvos_um_alvo CHECK (num_nonnulls(oportunidade_id, habilidade_publicada_id) = 1)
);

-- Um mesmo item só pode ser salvo uma vez por usuário (os índices também servem a busca por usuário).
CREATE UNIQUE INDEX uk_itens_salvos_oportunidade
    ON itens_salvos (usuario_id, oportunidade_id) WHERE oportunidade_id IS NOT NULL;
CREATE UNIQUE INDEX uk_itens_salvos_habilidade_publicada
    ON itens_salvos (usuario_id, habilidade_publicada_id) WHERE habilidade_publicada_id IS NOT NULL;
-- Para o CASCADE ao apagar o item.
CREATE INDEX idx_itens_salvos_oportunidade ON itens_salvos (oportunidade_id);
CREATE INDEX idx_itens_salvos_habilidade_publicada ON itens_salvos (habilidade_publicada_id);

-- Conexão entre dois usuários.
CREATE TABLE conexoes (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitante_id  bigint      NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    destinatario_id bigint      NOT NULL REFERENCES usuarios (id) ON DELETE CASCADE,
    status          varchar(20) NOT NULL DEFAULT 'PENDENTE',
    criado_em       timestamptz NOT NULL DEFAULT now(),
    atualizado_em   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_conexoes_par UNIQUE (solicitante_id, destinatario_id),
    CONSTRAINT ck_conexoes_status CHECK (status IN ('PENDENTE', 'ACEITA', 'RECUSADA')),
    CONSTRAINT ck_conexoes_distintos CHECK (solicitante_id <> destinatario_id)
);

-- Impede também o par invertido (B->A quando já existe A->B).
CREATE UNIQUE INDEX uk_conexoes_par_sem_ordem
    ON conexoes (LEAST(solicitante_id, destinatario_id), GREATEST(solicitante_id, destinatario_id));
CREATE INDEX idx_conexoes_destinatario ON conexoes (destinatario_id);
